language: node_js
node_js:
  - "node"
before_deploy: "rm -rf node_modules"
deploy:
  provider: azure_web_apps
  # username uses travis environment variable AZURE_WA_USERNAME
  # password uses travis environment variable AZURE_WA_PASSWORD
  # site uses travis environment variable AZURE_WA_SITE
  skip_cleanup: true
  # Note - Turning verbose on with azure_web_apps will print the password to the console :S
  # verbose: true
  on:
    branch: master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  firefox: "latest"
before_script:
  - npm run build-prod
  - git fetch --unshallow || true
  - git fetch origin "+refs/heads/*:refs/remotes/origin/*"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start