language: node_js
node_js:
  - "node"
before_deploy: "rimraf node_modules"
deploy:
  provider: azure_web_apps
  username: vivmaha
  # password: Uses travis environment variable AZURE_WA_PASSWORD
  site: notesbyv
  skip_cleanup: true
  on:
    branch: master
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
  - npm run build-travis